### ISSUE TITLE
Error message when trying to use the tool

### ISSUE THREAD

**Issue by GodSponge** [fhrach4/BooruGet#2]
I'm using the format specified in the readme: ``python BooruGet "search_term1 search_term2"`` but I get an error every time it runs.

    Traceback (most recent call last):
      File "D:\BooruGet\BooruGet", line 170, in <module>
        main()
      File "D:\\BooruGet\BooruGet", line 129, in main
        init_directories(arg['search'], arg['out_dir'])
      File "D:\\BooruGet\BooruGet", line 27, in init_directories
        os.mkdir(out_dir)
    FileNotFoundError: [WinError 3] The system cannot find the path specified: ''

My config is like this:

      username:myusername
      apikey:
      out_dir:"D:\BooruGet\downloads"

I don't have an apikey because i'm not using danbooru

Am I doing something wrong here or is there a bug?

**Comment by fhrach4** [comment]
I'll be honest, I forgot I even had this published to my Github account. I wrote this 10 years ago when I was in university and haven't looked at the code since. The chances if it working are pretty slim.

That said, looking at your error message it looks like the `out_dir` may not exist. I don't remember if it will create it automatically, so, you could try manually creating the directory structure.

**Comment by GodSponge** [comment]
Wow, I didn't even pay attention to how old the app was. No wonder it doesn't work quite right. Thanks for the reply. :)
